bill/urls.py
from django.urls import path

urlpatterns = []

from .views import (
    BillList,
    BillDetail,
    BillCreate,
    BillUpdate,
    BillDelete,
    MaterializedView,
    MaterializedViewExportExcel,
    SalesEntryViewExportExcel,
    ReturnEntryViewExportExcel,
    IncrementBillPrintCount,
    MarkBillVoid,
    CustomerWiseSalesInvoiceRegister,
    PartyWiseSalesInvoiceRegister,
    SalesInvoiceSummaryRegister,
    SalesInvoiceAnalysis,
    PaymentModeSummary,
)

urlpatterns += [
    path("bill/", BillList.as_view(), name="bill_list"),
    path(
        "invoice-summary-register",
        SalesInvoiceSummaryRegister.as_view(),
        name="invoice_summary_register",
    ),
    path("bill/<int:pk>/", BillDetail.as_view(), name="bill_detail"),
    path("bill/create/", BillCreate.as_view(), name="bill_create"),
    path("bill/<int:pk>/update/", BillUpdate.as_view(), name="bill_update"),
    path("bill/delete", BillDelete.as_view(), name="bill_delete"),
    path("salebook/view/", MaterializedView.as_view(), name="materialized_view"),
    path(
        "bill/print/count/increment/",
        IncrementBillPrintCount.as_view(),
        name="increment_bill_print_count",
    ),
    path("bill/void/<int:id>", MarkBillVoid.as_view(), name="mark_bill_void"),
    path(
        "materialized/export/",
        MaterializedViewExportExcel.as_view(),
        name="materialized_export",
    ),
    # path(
    #     "sales/export/",
    #     SalesEntryViewExportExcel.as_view(),
    #     name="sales_export",
    # ),
    path(
        "cws/",
        CustomerWiseSalesInvoiceRegister.as_view(),
        name="customer_wise_sales",
    ),
    path(
        "pws/",
        PartyWiseSalesInvoiceRegister.as_view(),
        name="party_wise_sales",
    ),
    path("sia/", SalesInvoiceAnalysis.as_view(), name="sales_invoice_analysis"),
    path("pms/", PaymentModeSummary.as_view(), name="payment_mode_summary")
    # path(
    #     "returns/export/",
    #     ReturnEntryViewExportExcel.as_view(),
    #     name="returns_export",
    # ),
]

from .views import (
    TblTaxEntryList,
    TblTaxEntryDetail,
    TblTaxEntryCreate,
    TblTaxEntryUpdate,
    TblTaxEntryDelete,
)

urlpatterns += [
    path("tbltaxentry/", TblTaxEntryList.as_view(), name="tbltaxentry_list"),
    path(
        "tbltaxentry/<int:pk>/", TblTaxEntryDetail.as_view(), name="tbltaxentry_detail"
    ),
    path("tbltaxentry/create/", TblTaxEntryCreate.as_view(), name="tbltaxentry_create"),
    path(
        "tbltaxentry/<int:pk>/update/",
        TblTaxEntryUpdate.as_view(),
        name="tbltaxentry_update",
    ),
    path("tbltaxentry/delete", TblTaxEntryDelete.as_view(), name="tbltaxentry_delete"),
]

from .views import (
    TblSalesEntryList,
    TblSalesEntryDetail,
    TblSalesEntryCreate,
    TblSalesEntryUpdate,
    TblSalesEntryDelete,
)

urlpatterns += [
    path("tblsalesentry/", TblSalesEntryList.as_view(), name="tblsalesentry_list"),
    path(
        "tblsalesentry/<int:pk>/",
        TblSalesEntryDetail.as_view(),
        name="tblsalesentry_detail",
    ),
    path(
        "tblsalesentry/create/",
        TblSalesEntryCreate.as_view(),
        name="tblsalesentry_create",
    ),
    path(
        "tblsalesentry/<int:pk>/update/",
        TblSalesEntryUpdate.as_view(),
        name="tblsalesentry_update",
    ),
    path(
        "tblsalesentry/delete",
        TblSalesEntryDelete.as_view(),
        name="tblsalesentry_delete",
    ),
]

from .views import (
    TablReturnEntryList,
    TablReturnEntryDetail,
    TablReturnEntryCreate,
    TablReturnEntryUpdate,
    TablReturnEntryDelete,
)

urlpatterns += [
    path(
        "tablreturnentry/", TablReturnEntryList.as_view(), name="tablreturnentry_list"
    ),
    path(
        "tablreturnentry/<int:pk>/",
        TablReturnEntryDetail.as_view(),
        name="tablreturnentry_detail",
    ),
    path(
        "tablreturnentry/create/",
        TablReturnEntryCreate.as_view(),
        name="tablreturnentry_create",
    ),
    path(
        "tablreturnentry/<int:pk>/update/",
        TablReturnEntryUpdate.as_view(),
        name="tablreturnentry_update",
    ),
    path(
        "tablreturnentry/delete",
        TablReturnEntryDelete.as_view(),
        name="tablreturnentry_delete",
    ),
]

root/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    # path("", include("bill.urls")),
    path("", include("organization.urls")),
    path("", include("user.urls")),
    path("", include("product.urls")),
    path("", include("bill.urls")),
    path("api/", include("api.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .views import (
    UserCreate,
    UserDelete,
    UserDetail,
    UserList,
    UserUpdate,
    logout_user,
)


app_name = "user"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login_view"),
    path("logout/", logout_user, name="logout"),
]


urlpatterns += [
    path("user/", UserList.as_view(), name="user_list"),
    path("user/<int:pk>/", UserDetail.as_view(), name="user_detail"),
    path("user/create/", UserCreate.as_view(), name="user_create"),
    path("user/<int:pk>/update/", UserUpdate.as_view(), name="user_update"),
    path("user/delete", UserDelete.as_view(), name="user_delete"),
]

from .views import (
    CustomerList,
    CustomerDetail,
    CustomerCreate,
    CustomerUpdate,
    CustomerDelete,
)

urlpatterns += [
    path("customer/", CustomerList.as_view(), name="customer_list"),
    path("customer/<int:pk>/", CustomerDetail.as_view(), name="customer_detail"),
    path("customer/create/", CustomerCreate.as_view(), name="customer_create"),
    path("customer/<int:pk>/update/", CustomerUpdate.as_view(), name="customer_update"),
    path("customer/delete", CustomerDelete.as_view(), name="customer_delete"),
]

from .views import (
    AgentCreate,
    AgentDelete,
    AgentList,
    AgentUpdate,
)


urlpatterns += [
    path("agent/", AgentList.as_view(), name="agent_list"),
    path("agent/create/", AgentCreate.as_view(), name="agent_create"),
    path("agent/<int:pk>/update/", AgentUpdate.as_view(), name="agent_update"),
    path("agent/delete", AgentDelete.as_view(), name="agent_delete"),
]

user/models.py
import datetime
import random
import uuid

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from organization.models import Branch, Organization
from root.utils import BaseModel


class User(AbstractUser, BaseModel):
    full_name = models.CharField(max_length=255, null=False, blank=False)
    email = models.EmailField(max_length=255, unique=True, null=False, blank=False)
    image = models.ImageField(upload_to="user/images/", null=True, blank=True)
    phone_number = models.CharField(max_length=255, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    organization = models.ForeignKey(Organization, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.full_name} - ({self.email})"

    def save(self, *args, **kwargs):
        if not self.email:
            self.email = f"{self.username}@periwin.com"

        super().save(*args, **kwargs)


class Customer(BaseModel):
    name = models.CharField(max_length=255, verbose_name="Customer Name")
    tax_number = models.CharField(
        max_length=255, verbose_name="PAN/VAT Number", null=True, blank=True
    )
    address = models.CharField(max_length=255, null=True, blank=True)
    contact_number = models.CharField(max_length=255, null=True, blank=True)
    created_by = models.ForeignKey(
        User, null=True, on_delete=models.SET_NULL, blank=True
    )
    email = models.EmailField(null=True, blank=True)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.name} ({self.contact_number})"


class ForgetPassword(BaseModel):
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    email = models.EmailField(max_length=255)
    token = models.CharField(max_length=255, blank=True)
    is_used = models.BooleanField(default=False)
    key = models.UUIDField(editable=False, blank=True)
    expiry_date = models.DateTimeField(blank=True)
    mail_sent = models.BooleanField(default=False)
    mail_sent_date = models.DateTimeField(blank=True, null=True)
    expired = models.BooleanField(default=False)

    def __str__(self):
        return self.email

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = self.generate_token()
            self.key = self.generate_key()
            self.expiry_date = datetime.datetime.now() + datetime.timedelta(hours=24)
        super().save(*args, **kwargs)

    def generate_token(self):
        return random.randint(100000, 999999)

    def generate_key(self):
        return uuid.uuid1(self.token)


@receiver(post_save, sender=ForgetPassword)
def send_mail_to_user(sender, instance, created, **kwargs):
    if created:
        ForgetPassword.objects.filter(email=instance.email, expired=False).exclude(
            id=instance.id
        ).update(expired=True)
        send_mail(
            "Reset Password",
            "Your token is {}".format(instance.token),
            settings.EMAIL_HOST_USER,
            [
                instance.email,
            ],
            fail_silently=True,
        )
        instance.mail_sent = True
        instance.mail_sent_date = datetime.datetime.now()
        instance.save()

user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from root.forms import BaseForm  # optional


User = get_user_model()

user_fields = ["full_name", "username"]


class UserCreateForm(BaseForm, UserCreationForm):
    class Meta:
        model = User
        fields = ["username"] + user_fields


class AdminForm(BaseForm, UserCreationForm):
    # password1 = None  # Standard django password input

    class Meta:
        model = User
        fields = ["full_name", "username"]

    def clean_password(self):
        return self.clean_password


class UserForm(BaseForm, UserCreationForm):
    # password1 = None  # Standard django password input
    password2 = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password1"].widget = forms.HiddenInput()
        self.fields["password1"].required = False
        self.fields["username"].label = "Usercode"

    class Meta:
        model = User
        fields = ["full_name", "username"]

    def clean_password(self):
        return self.clean_password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["username"])
        if commit:
            user.save()
        return user


from .models import Customer


class CustomerForm(BaseForm, forms.ModelForm):
    class Meta:
        model = Customer
        fields = "__all__"
        exclude = [
            "created_at",
            "updated_at",
            "status",
            "is_deleted",
            "sorting_order",
            "is_featured",
            "created_by",
            "email",
        ]

api/views/user.py
from rest_framework_simplejwt.views import TokenObtainPairView
from django.contrib.auth import get_user_model

from user.models import Customer
from ..serializers.user import CustomTokenPairSerializer, CustomerSerializer

from rest_framework.viewsets import ModelViewSet

User = get_user_model()


class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenPairSerializer


class CustomerAPI(ModelViewSet):
    serializer_class = CustomerSerializer
    model = Customer
    queryset = Customer.objects.active()
    pagination_class = None

user/views.py
from django.contrib.auth import get_user_model, logout
from django.contrib.auth.models import Group
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    View,
)
from root.utils import DeleteMixin, remove_from_DB
from user.permission import IsAdminMixin

from .forms import UserCreateForm, UserForm, AdminForm


User = get_user_model()


class UserMixin(IsAdminMixin):
    model = User
    form_class = AdminForm
    paginate_by = 50
    queryset = User.objects.filter(status=True)
    success_url = reverse_lazy("user:user_list")
    search_lookup_fields = ["username", "email", "full_name"]


class UserList(UserMixin, ListView):
    template_name = "user/user_list.html"
    queryset = User.objects.filter(is_superuser=True, status=True, is_deleted=False)

    def get_queryset(self, *args, **kwargs):
        queryset = self.queryset.exclude(id=self.request.user.id)
        return queryset


class UserDetail(UserMixin, DetailView):
    template_name = "user/user_detail.html"


class UserCreate(UserMixin, CreateView):
    template_name = "create.html"

    def form_valid(self, form):
        form.instance.is_superuser = True
        form.instance.is_staff = True
        form.instance.organization = self.request.user.organization

        object = form.save()
        group = Group.objects.get(name="admin")
        object.groups.add(group)
        return super().form_valid(form)


class UserAdmin(UserMixin, CreateView):
    template_name = "create.html"


class UserUpdate(UserMixin, UpdateView):
    template_name = "update.html"


class UserDelete(UserMixin, View):
    def get(self, request):
        status = remove_from_DB(self, request)
        return JsonResponse({"deleted": status})


def logout_user(request):
    logout(request)
    return redirect(reverse_lazy("user:login_view"))


from django.db import transaction
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
    View,
)
from root.utils import DeleteMixin
from .models import Customer
from .forms import CustomerForm


class CustomerMixin(IsAdminMixin):
    model = Customer
    form_class = CustomerForm
    paginate_by = 50
    queryset = Customer.objects.filter(status=True, is_deleted=False)
    success_url = reverse_lazy("user:customer_list")
    search_lookup_fields = ["name", "tax_number", "contact_number", "email"]


class CustomerList(CustomerMixin, ListView):
    template_name = "customer/customer_list.html"
    queryset = Customer.objects.active()


class CustomerDetail(CustomerMixin, DetailView):
    template_name = "customer/customer_detail.html"


class CustomerCreate(CustomerMixin, CreateView):
    template_name = "create.html"


class CustomerUpdate(CustomerMixin, UpdateView):
    template_name = "update.html"


class CustomerDelete(CustomerMixin, DeleteMixin, View):
    pass


class AgentMixin(IsAdminMixin):
    model = User
    form_class = UserForm
    paginate_by = 50
    queryset = User.objects.filter(status=True, is_deleted=False)
    success_url = reverse_lazy("user:agent_list")
    search_lookup_fields = ["username", "email", "full_name"]


class AgentList(AgentMixin, ListView):
    template_name = "agent/agent_list.html"
    queryset = User.objects.filter(
        groups__name__in=["agent"], status=True, is_deleted=False
    )


class AgentCreate(AgentMixin, CreateView):
    template_name = "create.html"

    def form_valid(self, form):

        form.instance.is_superuser = False
        form.instance.is_staff = True
        object = form.save()

        group = Group.objects.get(name="agent")
        object.groups.add(group)
        return super().form_valid(form)


class AgentUpdate(AgentMixin, UpdateView):
    template_name = "update.html"


class AgentDelete(AgentMixin, DeleteMixin, View):
    pass

templates/user/user_list.html
{%extends 'base.html'%}
{% block pagetitle %}User List {% endblock %}
{% block home %} {% url 'user:user_list' %} {% endblock %}
{% block title %}User List {% endblock %}
{% block title_bar %}
{% include 'components/title_bar.html' with title="Admin List" create="yes" %}
{%endblock%}
{% block content %}
<div class="card">
   <!--begin::Card header-->
   {%if object_list%}
    {% include 'components/search_filter.html' with search_title="Search User"  %}
   {%endif%}
   <div class="card-body pt-0">
      <!--begin::Table-->
      <div id="kt_customers_table_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
         <div class="table-responsive">
            <table class="table align-middle table-row-dashed fs-6 gy-5 dataTable no-footer" id="kt_customers_table">
               <!--begin::Table head-->
               {%if object_list%}
               <thead>
                  <!--begin::Table row-->
                  <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                     <th class="w-10px pe-2 sorting_disabled" rowspan="1" colspan="1" aria-label="
                        " style="width: 29.25px;">
                        <div class="form-check form-check-sm form-check-custom form-check-solid me-3">
                           <input class="form-check-input" type="checkbox" data-kt-check="true"
                              data-kt-check-target="#kt_customers_table .form-check-input" value="1">
                        </div>
                     </th>
                     <th class="min-w-125px sorting" tabindex="0" >Full Name</th>
                     <th class="min-w-125px sorting" tabindex="0" > Email</th>
                     <th class="min-w-125px sorting" tabindex="0" >  Username</th>
                     <th class="min-w-125px sorting" tabindex="0" > Status</th>
                     <th class="text-end min-w-70px sorting_disabled" rowspan="1" colspan="1" aria-label="Actions"
                        style="width: 125.287px;">Actions</th>
                  </tr>
                  <!--end::Table row-->
               </thead>
               {%endif%}
               <tbody class="fw-bold text-gray-600">
                  {% for object in object_list %}
                  <tr class="odd" id="obj-{{object.pk}}">
                     <td>
                        <div class="form-check form-check-sm form-check-custom form-check-solid">
                           <input class="form-check-input" type="checkbox" value="1">
                        </div>
                     </td>
                     <td>{{object.full_name}}</td>
                     <td>{{object.email}}</td>
                     <td>{{object.username}}</td>
                     <td>{%include 'components/status.html' with status=object.status%}</td>
                     <td class="text-end">
                        <a href="#" class="btn btn-sm btn-light btn-active-light-primary" data-kt-menu-trigger="click"
                           data-kt-menu-placement="bottom-end">
                           Actions
                           <!--begin::Svg Icon | path: icons/duotune/arrows/arr072.svg-->
                           <span class="svg-icon svg-icon-5 m-0">
                              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                 <path
                                    d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z"
                                    fill="black"></path>
                              </svg>
                           </span>
                           <!--end::Svg Icon-->
                        </a>
                        <!--begin::Menu-->
                        <div
                           class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-125px py-4"
                           data-kt-menu="true" style="">
                           <!--begin::Menu item-->
                           <!--end::Menu item-->
                           <!--begin::Menu item-->
                           <div class="menu-item px-3">
                              <a href="{% url 'user:user_update' object.pk %}" class="menu-link px-3"
                                 data-kt-customer-table-filter="update_row">Update</a>
                           </div>
                           <div class="menu-item px-3">
                              <a onclick="remove({{object.pk}},'{% url "user:user_delete" %}','{{object}}',)" class="menu-link px-3" id="obj"
                              data-kt-customer-table-filter="delete_row">Delete</a>
                           </div>

                           <!--end::Menu item-->
                        </div>
                     </td>
                  </tr>
                  {%empty%}
{% include 'components/empty.html' with title="Admins" %}
                  {% endfor %}
               </tbody>
               <!--end::Table body-->
            </table>
         </div>
         {%if object_list%}
            {% include 'pagination.html' %}
         {%endif%}
      </div>
      <!--end::Table-->
   </div>
   <!--end::Card body-->
</div>
<script></script>
{% endblock %}