bill/urls.py
from django.urls import path

urlpatterns = []

from .views import (
    BillList,
    BillDetail,
    BillCreate,
    BillUpdate,
    BillDelete,
    MaterializedView,
    MaterializedViewExportExcel,
    SalesEntryViewExportExcel,
    ReturnEntryViewExportExcel,
    IncrementBillPrintCount,
    MarkBillVoid,
    CustomerWiseSalesInvoiceRegister,
    PartyWiseSalesInvoiceRegister,
    SalesInvoiceSummaryRegister,
    SalesInvoiceAnalysis,
    PaymentModeSummary,
)

urlpatterns += [
    path("bill/", BillList.as_view(), name="bill_list"),
    path(
        "invoice-summary-register",
        SalesInvoiceSummaryRegister.as_view(),
        name="invoice_summary_register",
    ),
    path("bill/<int:pk>/", BillDetail.as_view(), name="bill_detail"),
    path("bill/create/", BillCreate.as_view(), name="bill_create"),
    path("bill/<int:pk>/update/", BillUpdate.as_view(), name="bill_update"),
    path("bill/delete", BillDelete.as_view(), name="bill_delete"),
    path("salebook/view/", MaterializedView.as_view(), name="materialized_view"),
    path(
        "bill/print/count/increment/",
        IncrementBillPrintCount.as_view(),
        name="increment_bill_print_count",
    ),
    path("bill/void/<int:id>", MarkBillVoid.as_view(), name="mark_bill_void"),
    path(
        "materialized/export/",
        MaterializedViewExportExcel.as_view(),
        name="materialized_export",
    ),
    # path(
    #     "sales/export/",
    #     SalesEntryViewExportExcel.as_view(),
    #     name="sales_export",
    # ),
    path(
        "cws/",
        CustomerWiseSalesInvoiceRegister.as_view(),
        name="customer_wise_sales",
    ),
    path(
        "pws/",
        PartyWiseSalesInvoiceRegister.as_view(),
        name="party_wise_sales",
    ),
    path("sia/", SalesInvoiceAnalysis.as_view(), name="sales_invoice_analysis"),
    path("pms/", PaymentModeSummary.as_view(), name="payment_mode_summary")
    # path(
    #     "returns/export/",
    #     ReturnEntryViewExportExcel.as_view(),
    #     name="returns_export",
    # ),
]

from .views import (
    TblTaxEntryList,
    TblTaxEntryDetail,
    TblTaxEntryCreate,
    TblTaxEntryUpdate,
    TblTaxEntryDelete,
)

urlpatterns += [
    path("tbltaxentry/", TblTaxEntryList.as_view(), name="tbltaxentry_list"),
    path(
        "tbltaxentry/<int:pk>/", TblTaxEntryDetail.as_view(), name="tbltaxentry_detail"
    ),
    path("tbltaxentry/create/", TblTaxEntryCreate.as_view(), name="tbltaxentry_create"),
    path(
        "tbltaxentry/<int:pk>/update/",
        TblTaxEntryUpdate.as_view(),
        name="tbltaxentry_update",
    ),
    path("tbltaxentry/delete", TblTaxEntryDelete.as_view(), name="tbltaxentry_delete"),
]

from .views import (
    TblSalesEntryList,
    TblSalesEntryDetail,
    TblSalesEntryCreate,
    TblSalesEntryUpdate,
    TblSalesEntryDelete,
)

urlpatterns += [
    path("tblsalesentry/", TblSalesEntryList.as_view(), name="tblsalesentry_list"),
    path(
        "tblsalesentry/<int:pk>/",
        TblSalesEntryDetail.as_view(),
        name="tblsalesentry_detail",
    ),
    path(
        "tblsalesentry/create/",
        TblSalesEntryCreate.as_view(),
        name="tblsalesentry_create",
    ),
    path(
        "tblsalesentry/<int:pk>/update/",
        TblSalesEntryUpdate.as_view(),
        name="tblsalesentry_update",
    ),
    path(
        "tblsalesentry/delete",
        TblSalesEntryDelete.as_view(),
        name="tblsalesentry_delete",
    ),
]

from .views import (
    TablReturnEntryList,
    TablReturnEntryDetail,
    TablReturnEntryCreate,
    TablReturnEntryUpdate,
    TablReturnEntryDelete,
)

urlpatterns += [
    path(
        "tablreturnentry/", TablReturnEntryList.as_view(), name="tablreturnentry_list"
    ),
    path(
        "tablreturnentry/<int:pk>/",
        TablReturnEntryDetail.as_view(),
        name="tablreturnentry_detail",
    ),
    path(
        "tablreturnentry/create/",
        TablReturnEntryCreate.as_view(),
        name="tablreturnentry_create",
    ),
    path(
        "tablreturnentry/<int:pk>/update/",
        TablReturnEntryUpdate.as_view(),
        name="tablreturnentry_update",
    ),
    path(
        "tablreturnentry/delete",
        TablReturnEntryDelete.as_view(),
        name="tablreturnentry_delete",
    ),
]

organization/urls.py
from django.urls import path
from organization.views import IndexView

from .views import (
    OrganizationCreate,
    OrganizationDelete,
    OrganizationDetail,
    OrganizationUpdate,
    StaticPageCreate,
    StaticPageDelete,
    StaticPageDetail,
    StaticPageList,
    StaticPageUpdate,
)


app_name = "org"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
]


urlpatterns += [
    path("organization/", OrganizationDetail.as_view(), name="organization_detail"),
    path(
        "organization/create/", OrganizationCreate.as_view(), name="organization_create"
    ),
    path(
        "organization/update/",
        OrganizationUpdate.as_view(),
        name="organization_update",
    ),
    path(
        "organization/delete", OrganizationDelete.as_view(), name="organization_delete"
    ),
]


urlpatterns += [
    path("staticpage/", StaticPageList.as_view(), name="staticpage_list"),
    path("staticpage/<int:pk>/", StaticPageDetail.as_view(), name="staticpage_detail"),
    path("staticpage/create/", StaticPageCreate.as_view(), name="staticpage_create"),
    path(
        "staticpage/<int:pk>/update/",
        StaticPageUpdate.as_view(),
        name="staticpage_update",
    ),
    path("staticpage/delete", StaticPageDelete.as_view(), name="staticpage_delete"),
]

from .views import BranchList,BranchDetail,BranchCreate,BranchUpdate,BranchDelete
urlpatterns += [
path('branch/', BranchList.as_view(), name='branch_list'),
path('branch/<int:pk>/', BranchDetail.as_view(), name='branch_detail'),
path('branch/create/', BranchCreate.as_view(), name='branch_create'),
path('branch/<int:pk>/update/', BranchUpdate.as_view(), name='branch_update'),
path('branch/delete', BranchDelete.as_view(), name='branch_delete'),
]
               

root/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    # path("", include("bill.urls")),
    path("", include("organization.urls")),
    path("", include("user.urls")),
    path("", include("product.urls")),
    path("", include("bill.urls")),
    path("api/", include("api.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/branch/branch_list.html
{%extends 'base.html'%}
{% block pagetitle %}Branch List {% endblock %}
{% block home %} {% url 'branch_list' %} {% endblock %}
{% block title %}Branch List {% endblock %}
{% block content %}
 {% include 'components/title_bar.html' with title=' Branch List ' create='/create/'  %}
                <div class="card">

                {% include 'components/search_filter.html' with  search_title="Search Branch" create_url="org:branch_create" create_button="Add Branch" %} 


    <div class="card-body pt-0">
    <!--begin::Table-->
    <div id="kt_customers_table_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
      <div class="table-responsive">
        <table class="table align-middle table-row-dashed fs-6 gy-5 dataTable no-footer" id="kt_customers_table">
          <!--begin::Table head-->
          {%if object_list%}
          <thead>
            <!--begin::Table row-->
            <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
              <th class="min-w-125px sorting" tabindex="0" > Branch Code</th>

              <th class="min-w-125px sorting" tabindex="0" > Name</th>
              <th class="min-w-125px sorting" tabindex="0" > Address</th>
              <th class="min-w-125px sorting" tabindex="0" > Contact Number</th>
              <th class="min-w-125px sorting" tabindex="0" > Status</th>
              <th class="min-w-125px sorting" tabindex="0" > Branch Manager</th>

              <th class="text-end min-w-70px sorting_disabled" rowspan="1" colspan="1" aria-label="Actions"
                style="width: 125.287px;">Actions</th>
            </tr>
            <!--end::Table row-->
          </thead>
          {%endif%}
          <tbody class="fw-bold text-gray-600">

          {% for object in object_list %}
             <tr class="odd" id="obj-{{object.pk}}">

                <td>{{object.branch_code}}</td>

                <td>{{object.name}}</td>
                <td>{{object.address}}</td>
                <td>{{object.contact_number}}</td>
                <td>{% include 'components/status.html' with status=object.status%}</td>
                <td>{{object.branch_manager}}</td>
                <td class="text-end">
                <a href="#" class="btn btn-sm btn-light btn-active-light-primary" data-kt-menu-trigger="click"
                                data-kt-menu-placement="bottom-end">Actions
                                <!--begin::Svg Icon | path: icons/duotune/arrows/arr072.svg-->
                                <span class="svg-icon svg-icon-5 m-0">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                    <path
                                        d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z"
                                        fill="black"></path>
                                    </svg>
                                </span>
                                <!--end::Svg Icon-->
                                </a>
                                <!--begin::Menu-->
                                <div
                                class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-125px py-4"
                                data-kt-menu="true" style="">
                                <!--begin::Menu item-->
                                <!--end::Menu item-->
                                <!--begin::Menu item-->
                                <div class="menu-item px-3">
                                    <a href="{% url 'org:branch_update' object.pk %}" class="menu-link px-3"
                                    data-kt-customer-table-filter="update_row">Update</a>
                                </div>
                                <div class="menu-item px-3">
                                    <a onclick="remove({{object.pk}},'{% url "org:branch_delete" %}','{{object}}',)" class="menu-link px-3" id="obj"
                                    data-kt-customer-table-filter="delete_row">Delete</a>
                                </div>
'
                  <!--end::Menu item-->
                </div>
                </td>
             </tr>
             {%empty%}
             {% include 'components/empty.html' with  title="Branch"%}
              {% endfor %}

          </tbody>
          <!--end::Table body-->
        </table>
      </div>
    {%if object_list%}
      {% include 'pagination.html' %}
    {%endif%}
    </div>
    <!--end::Table-->
  </div>
  <!--end::Card body-->
</div>

<script>
</script>

{% endblock %}